### ISSUE TITLE
{{ghost_head}} not working on error page in Ghost 0.6.0

### ISSUE THREAD

**Issue by franklouwers** [Kikobeats/uno-zen#16]
It seems Ghost 0.6.0 changed changed something that caused {{ghost_head}} to break in Ghost 0.6.0. I don't know yet if this a Ghost bug or a theme bug, but you are probably more into Ghost development than I am :)

**Comment by Kikobeats** [comment]
the last stable version that I know that works fine is `0.5.10`. If you can report me more information I can migrate it easily

**Comment by franklouwers** [comment]
Yes indeed, it works fine on 0.5.10. But on 0.6.0, if you go to a non-existing page, Ghost/Express/Node throws this error:

```
ERROR: [error.hbs] Cannot read property '0' of undefined
 Error whilst rendering error page
 Error template has an error
 TypeError: [error.hbs] Cannot read property '0' of undefined
    at Object.ghost_head (/Users/frank/src/openminds/frank/ghostblog/core/server/helpers/ghost_head.js:269:31)
    at Object.<anonymous> (/Users/frank/src/openminds/frank/ghostblog/core/server/helpers/index.js:60:28)
    at Function.Waiter.resolve (/Users/frank/src/openminds/frank/ghostblog/node_modules/express-hbs/lib/async.js:83:3)
    at Object.<anonymous> (/Users/frank/src/openminds/frank/ghostblog/node_modules/express-hbs/lib/hbs.js:394:18)
    at Object.eval (eval at <anonymous> (/Users/frank/src/openminds/frank/ghostblog/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:209:23), <anonymous>:11:166)
    at ret (/Users/frank/src/openminds/frank/ghostblog/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:144:30)
    at ret (/Users/frank/src/openminds/frank/ghostblog/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:462:21)
    at renderTemplate (/Users/frank/src/openminds/frank/ghostblog/node_modules/express-hbs/lib/hbs.js:481:13)
    at render (/Users/frank/src/openminds/frank/ghostblog/node_modules/express-hbs/lib/hbs.js:529:5)
    at renderIt (/Users/frank/src/openminds/frank/ghostblog/node_modules/express-hbs/lib/hbs.js:591:18)
```

When I remove {{ghost_head}} (on line 9), it works, so it must be something there. Either ghost_head isn't supported anymore on error pages?

It's probably a Ghost bug ....

**Comment by Kikobeats** [comment]
hmmm I don't know, but `ghost_head` exist as theme helper already in `0.6.0`:

http://themes.ghost.org/v0.6.0/docs/ghost_head

Althought `0.6.0` introduces many changes, so I don't know if is a Ghost bug or is a intentional behavior

More information about the changes here: http://dev.ghost.org/ghost-0-6-0/

**Comment by franklouwers** [comment]
Seems like a bug: https://github.com/TryGhost/Ghost/issues/5146#issuecomment-93337927

**Comment by Kikobeats** [comment]
@franklouwers `0.6.1` is out and resolve the problem, can you confirm it?
