### ISSUE TITLE
Not able to make it work on heroku

### ISSUE THREAD

**Issue by robincsamuel** [Kikobeats/uno-zen#39]
I can see everything working perfect on local env. But when i push to heroku, its not working. Heroku removes everything in the uno-zen directory but casper is fine.

Any idea?

**Comment by Kikobeats** [comment]
Not really. Try to see the terminal output from the heroku instance and paste it

**Comment by robincsamuel** [comment]
Here is the log,

``` bash
2015-08-05T13:42:36.917967+00:00 app[web.1]: 
2015-08-05T13:42:36.917978+00:00 app[web.1]:  Error: Failed to lookup view "index" in views directory "/app/content/themes/uno-zen"
2015-08-05T13:42:36.917975+00:00 app[web.1]:  Rendering Error Page 
2015-08-05T13:42:36.917973+00:00 app[web.1]: ERROR: Failed to lookup view "index" in views directory "/app/content/themes/uno-zen" 
2015-08-05T13:42:36.917977+00:00 app[web.1]:  Ghost caught a processing error in the middleware layer. 
2015-08-05T13:42:36.917981+00:00 app[web.1]:     at ServerResponse.res.render (/app/node_modules/express/lib/response.js:938:7)
2015-08-05T13:42:36.917980+00:00 app[web.1]:     at EventEmitter.app.render (/app/node_modules/express/lib/application.js:555:17)
2015-08-05T13:42:36.917987+00:00 app[web.1]:     at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:530:18)
2015-08-05T13:42:36.917983+00:00 app[web.1]:     at /app/core/server/controllers/frontend.js:223:25
2015-08-05T13:42:36.917986+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:454:31)
2015-08-05T13:42:36.917991+00:00 app[web.1]:     at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:187:10)
2015-08-05T13:42:36.917990+00:00 app[web.1]:     at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:177:16)
2015-08-05T13:42:36.917984+00:00 app[web.1]:     at tryCatcher (/app/node_modules/bluebird/js/main/util.js:24:31)
2015-08-05T13:42:36.917993+00:00 app[web.1]:     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/main/async.js:15:14)
2015-08-05T13:42:36.917989+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:646:14)
2015-08-05T13:42:36.917995+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:321:17) 
2015-08-05T13:42:36.920261+00:00 app[web.1]: 106.206.137.233 - - [05/Aug/2015:13:42:36 +0000] "GET / HTTP/1.1" 500 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36"
```

its deployed to http://robinz.herokuapp.com/

BTW, the theme folder `uno-zen` is empty, when i checked via heroku bash

**Comment by Kikobeats** [comment]
well, I think that maybe you have something in your `.gitignore` that avoid push the theme in the heroku server.

**Comment by Kikobeats** [comment]
I close this issue because is not related with the theme, but you can continue pasting logs and stuff

**Comment by robincsamuel** [comment]
Its working now. don't know what happened, i just renamed the directory and it works. Thanks

**Comment by Kikobeats** [comment]
you're welcome :)

**Comment by calekennedy** [comment]
@robincsamuel what directory did you rename? I'm having the same issue.

**Comment by robincsamuel** [comment]
I renamed the theme's root directory.
